[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Enable caching of all static assets for 1 year
  # Increase the `max-age` value to cache for a longer period
  # or set it to 0 to disable caching altogether
  for = "/static/**"
  [headers.values]
    cache-control = "public, max-age=31536000"

  # Prevent search engine indexing of the site
  # by adding the `X-Robots-Tag` header with a `noindex` value
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"
